from mobilizon_reshare.publishers.coordinators.recap_publishing.recap import (
    RecapCoordinator,
)


class DryRunRecapCoordinator(RecapCoordinator):
    """
    Coordinator to perform a dry-run on the event recap
    """

    def _send(self, content, recap_publication):
        """
        Overrides the Recap Coordinator _send on the assumption that _send is just a side effect publishing
        on a given platform. The report generated by RecapCoordinator should be sufficient to perform
        the dry-run print at CLI level.
        :param content:
        :param recap_publication:
        :return:
        """
        pass
